apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
  labels:
    app: shoppingapi
spec:
  selector:
    app: shoppingapi
  ports:
    - name: shoppingapi
      port: 80
      protocol: TCP
