apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-service
  labels:
    app: shoppingclient
spec:
  selector:
    app: shoppingclient
  ports:
    - name: shoppingclient
      nodePort: 30000
      port: 8001
      targetPort: 80
      protocol: TCP
  type: NodePort
